### ISSUE TITLE
Merge zerospeech21-vg branch?

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#104]
Don't want to rush you, @bhigy, but just wondering whether that branch could be merged yet. I was looking at #53 where you said that W&B disabling was already implemented, which would be a good starting point for fixing that issue, I would guess. I also see in https://github.com/spokenlanguage/platalea/compare/zerospeech21-vg that the paths have already diverged far enough that manual merging is necessary, which probably means we should not postpone too long, otherwise the pain will just grow exponentially ;) Take it from someone who has just spent the past 1,5 months merging two branches that had diverged for 2,5 years :D

**Comment by bhigy** [comment]
I would also have liked to merge but I first would like to discuss some of the changes we made, in particular to use pretrained features as input (see #103) which require some thinking/refactoring. An option in the meantime would be to cherry-pick the commit related to W&B if it is clean enough or do the changes again on master. As I expect the refactoring to take some time, I was also thinking about merging master in zerospeech21-vg branch to avoid diverging to much. Now should be a good time as the baseline for the challenge has been finalized.

**Comment by egpbos** [comment]
👍 merging master into the branch sounds like the best option, indeed.

**Comment by bhigy** [comment]
Done on the 31st of May. I will try to refactor the existing code to merge soon.

**Comment by bhigy** [comment]
Done. Creation of a test case covering SpokenCOCO dataset has been set as a separate issue to allow merging right away.
