### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#116]
5 tox tests fail on master in the latest test. There were no code changes since last passing test and also on my laptop tox still runs fine, so I expect the issue is with an updated dependency, most likely PyTorch itself. On CI, tox installs torch 1.9.0, while on my laptop I still had 1.8.1. We should probably just update the generated outcomes with the latest dependencies.

**Comment by bhigy** [comment]
Wouldn't it be better to fix pytorch version? We have had a few issues with new pytorch versions introducing errors and I don't really like the idea of the CI workflow breaking without us doing anything.

**Comment by bhigy** [comment]
I tried it in the zerospeech branch and I am hitting another issue similar to this: https://github.com/wandb/client/issues/2349. They are working on a fix that is not available yet.

**Comment by bhigy** [comment]
Fixed by pinning down torch version.
