### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#16]
The `soundfile` package is in requirements.txt, but not in setup.py, so won't be installed by pip install. We should add it there, since it was added to preprocessing in #11.

Related: do we need to keep requirements.txt for something specific? We had a recent discussion about this at the eScience Center: https://github.com/NLeSC/guide/issues/156. Our conclusion, based on a survey of common practices, that requirements.txt is often superfluous, except for instance when you use it for specifying package repositories/sources. I see that in this case that is actually done for `ursa`, but I'm not sure whether that dependency is actually used at all. It was originally used in the analysis subdirectory, but that was removed at some point in this repo.

Do you agree that we can remove requirements.txt?

**Comment by bhigy** [comment]
Let me add @gchrupala to the discussion as he might have some opinion on this.

**Comment by gchrupala** [comment]
My understanding is that for library code dependencies should be specified permissively in setup.py, while for code which reproduces a specific set of experiments/results we specify the exact versions of each dependency in requirements.txt. Currently platalea is both (which would mean using requirements.txt as the more strict option); I suppose we could separate it into library and experiment  code.

**Comment by egpbos** [comment]
Agreed, as discussed. For paper repos we'll use requirements.txt to specifically pin requirement versions and/or source repositories, for the general library we use setup.py as permissively as possible.

We could also call requirements.txt something different, for instance `requirements_paper_[identifier].txt` to make this more explicit.

For `platalea`, what does this mean? Should we make clear in the readme what paper(s) this requirements.txt corresponds to? Or should we remove it here and put it in a separate repo for that paper?
