### ISSUE TITLE
Find out and fix what's wrong in coverage

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#19]
Unfortunately, it seems like something has not gone right in #17 and hence in #4. I misread that the coverage went up to 80%, but it actually went down very slightly. Maybe not all the coverage reports are properly merging, maybe not all files are properly tracked (the experiment files for instance seem to be missing in the report), maybe something else is going on, but it seems very strange that coverage would go down when we now run all these experiments. Something to look into.

**Comment by bhigy** [comment]
What is the status of this issue?

**Comment by egpbos** [comment]
Indeed, it seems like each experiment overwrites previous coverage report files. If you look [here](https://codecov.io/gh/spokenlanguage/platalea/tree/9300bb094866f7b6541afdda6a061a78b820b3d4/platalea/experiments/flickr8k) for instance, you see that only the last experiment (`pip_seq`) was logged. We should find out how to either log multiple coverage runs, or run all experiments in one command.

**Comment by egpbos** [comment]
Ok, adding `--append` to the `coverage run` command fixed it, it now aggregates all info, see [this report](https://codecov.io/gh/spokenlanguage/platalea/tree/8a35cb81a4eed51c5708258b0aa1952f6b965d76). Our coverage is now up to 68%, nice!
