### ISSUE TITLE
Overtrain on 100-image subsample of full dataset to validate transformer architecture

### ISSUE THREAD

**Issue by cwmeijer** [spokenlanguage/platalea#27]
Do the same as in #26, but with bigger dataset. To be created in #25 .

**Comment by egpbos** [comment]
No longer need to build new dataset, we can just do this using the downsampling_factor parameter.

**Comment by egpbos** [comment]
Do we still need to do this?

**Comment by cwmeijer** [comment]
I don't think so. I created this at a time the transformer learning curves still was jumping around and didn't make sense. Now everything seems to work fine so no need for this.
