### ISSUE TITLE
Make sure label_encoders.pkl gets installed

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#35]
When doing `pip install .`, currently the file `label_encoders.pkl` does not get installed, despite it being in the MANIFEST.in file.

I also tried putting it in setup.py, with `package_data={'platalea': ['platalea/label_encoders.pkl']}`, but that doesn't work either.

**Comment by bhigy** [comment]
Temporarily went back to using the version from `flickr8k_root` to avoid errors.

**Comment by bhigy** [comment]
Unfortunately this makes the CI workflow fail... Fixing the installation of the file is probably the easiest solution.

**Comment by egpbos** [comment]
It should get fixed. Somehow the file does not get installed with pip install and I don't understand why.

A workaround for now could be to let platalea download it from Github itself. So put a `try` around the loading of the file and download it when the file not found exception is raised.

**Comment by bhigy** [comment]
As per https://www.remarkablyrestrained.com/python-setuptools-manifest-in/, I solved it by adding `setuptools_scm` package in `setup.py`.

**Comment by egpbos** [comment]
Great!
