### ISSUE TITLE
Fix tox on CI

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#37]
I was working on fixing CI some weeks ago. For that purpose, I had set up interactive SSH debugging with `tmate`. Continue this.

**Comment by cwmeijer** [comment]
Could you please add some info here so others could work on this or understand what's it about?
What is the purpose? What do you propose should be done to fix it?

**Comment by egpbos** [comment]
I was trying to set up `tox` for testing, so that you can easily call pytest to run the testsuite. This suite would consist of the experiments, like now (which are smoke tests, i.e. tests to see whether code runs at all, not whether it runs correctly), but could also include smaller unit tests if/when we encounter the need to add those.

I had it working on my laptop and on the Tilburg servers, but on Github Actions, these tests gave strange errors that I couldn't debug. Since I know of no way to replicate the Actions environment exactly on my machine (hurray for "free" cloud services ;)), I set up `tmate` to debug the Actions run itself directly. Using `tmate`, you can log in through `ssh` to the (virtual) machine running the CI job.

If you take out the `tmate` step in the CI recipe and let the `tox` test run again, you'll see the error (or not, if it magically solved itself by now). Then you can continue debugging it.

**Comment by egpbos** [comment]
Oh, one additional reason for wanting to setup tox/pytest was that I could then more easily run the tests from my debugger in VSCode (PyCharm would have similar automatic test detection). This was what I, in fact, actually used it for, when I was trying to debug the NaNs issue in the transformer, leading to the bugfix in PyTorch, which by now for some reason no longer seems to be necessary... Something we should check as well.

**Comment by egpbos** [comment]
Well, that was easy. Magically fixed itself. https://github.com/spokenlanguage/platalea/runs/1769272908?check_suite_focus=true

**Comment by egpbos** [comment]
I added all experiments to the tox job. All are working, except the last one. This exposes a bug in the config system.

This is because of the way experiments.config works in combination with how the test was written. The config module assumes it is loaded only once per run. However, because we load all experiments from a single test_experiments.py file, the config module is loaded for each test. Since pip_ind and pip_seq add the same config argument to the parser, the second one to do so causes a conflict:

```py
argparse.ArgumentError: argument --asr_model_dir: conflicting option string: --asr_model_dir
```

**Comment by egpbos** [comment]
Fixed it by replacing config.args with a factory function that generates a new parser on every script run.

**Comment by egpbos** [comment]
Added coverage and linting (flake8) to tox as well. This replaces all currently manually written out test commands in the run_experiments CI job, which can hence be removed from now on.

Nice side effect: we now have a good, officially recommended place for putting linting settings, namely the tox.ini file ([recommended here](https://flake8.pycqa.org/en/latest/user/configuration.html)). This is also a good place to add pylint settings, if we want to add that later.

The cool thing about this whole setup is that you can now also very easily run the test suite from your laptop.
