### ISSUE TITLE
Add automatic versioning

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#38]
Found this package [version-query](https://github.com/mbdevpl/version-query), may be useful, also for wandb logging.

**Comment by bhigy** [comment]
Can you quickly summaries what this does and how we can benefit from it?

**Comment by egpbos** [comment]
It automatically determines a version number based on git history, tags, and some other possible sources. This version number could then be used for logging, without having to make a tagged release or hacking together something that logs the git commit hash.

**Comment by bhigy** [comment]
Isn't the commit version more precise?

By the way, W&B seems to log the commit already (based on this doc: https://docs.wandb.com/library/init#save-the-git-commit).

**Comment by egpbos** [comment]
Commit is good too. Version-query uses that as well in case the package (repo) is not in a tagged state. It also adds whether the repo is clean (committed) or not (has some uncommitted edits).

**Comment by bhigy** [comment]
Ok, I didn't see that. Fine with me then.

**Comment by cwmeijer** [comment]
In my opinion, the commit version is good enough and I propose to close this issue.

**Comment by cwmeijer** [comment]
Do you agree, @egpbos ?

**Comment by egpbos** [comment]
Yep, fine.
