### ISSUE TITLE
Add experiments to the test scenarios

### ISSUE THREAD

**Issue by bhigy** [spokenlanguage/platalea#4]
I would add:
- asr/run.py
- mtl-asr/run.py
- mtl-st/run.py
- pip-ind/run.py (reusing trained asr and text-image models)
- pip-seq/run.py (reusing trained asr model)
- text-image/run.py
- jp/text-image/run.py

We need to check if that is not going to take to much time but it would cover the main experiments and architectures.

**Comment by egpbos** [comment]
To make sure it doesn't take too long, I will add the epochs parameter to the general config and set it up for use in all the experiments. That way, we can run it with just 1 epoch. Tested and working on at least asr now.

Are there experiments which must be run for a higher number of epochs to cover all relevant code?

**Comment by egpbos** [comment]
For testing proper code functionality, does it matter for the pip experiments whether we actually reuse asr and text-image models or would any model do? The latter would make things slightly easier (we don't have to take run order into account).

**Comment by egpbos** [comment]
Ah, of course it matters, the `pt` dumps are model specific :)

**Comment by egpbos** [comment]
`jp/text-image` has been removed, right?

**Comment by bhigy** [comment]
> To make sure it doesn't take too long, I will add the epochs parameter to the general config and set it up for use in all the experiments. That way, we can run it with just 1 epoch. Tested and working on at least asr now.
> 
> Are there experiments which must be run for a higher number of epochs to cover all relevant code?

Adding the `epochs` parameter to all experiments would be good indeed. One epoch should be enough for testing.

**Comment by bhigy** [comment]
> For testing proper code functionality, does it matter for the pip experiments whether we actually reuse asr and text-image models or would any model do? The latter would make things slightly easier (we don't have to take run order into account).

Are they running in parallel? Because my main concern with adding all the experiments is still time.

**Comment by bhigy** [comment]
> `jp/text-image` has been removed, right?

Yes.
