### ISSUE TITLE
CI ending in error

### ISSUE THREAD

**Issue by bhigy** [spokenlanguage/platalea#48]
Some changes done in relation to #37 have made the CI worflow fail due to the `tox` job. We should fix this even if it means removing that job for now.

**Comment by cwmeijer** [comment]
I will have a look at it. Hopefully this week. I'll assign myself as soon as I start working on it, so as long that hasn't happened yet, feel free to have a look at this item yourself (to everyone) and don't forget to assign yourself if you do.

**Comment by bhigy** [comment]
Fixed by removing tox from the workflow for the time being
